#!/bin/bash

set -eu

running_test() {
  tempdir=$(mktemp -d)
  trap "docker image rm chatapp_test_test ; [ -e $tempdir ] && rm -rf $tempdir" EXIT
  git archive --format=tar --prefix=chatapp_test/ "$1" | ( cd "$tempdir" && tar xf - )
  cd "$tempdir/chatapp_test"
  [ -f "./.env" ] || touch ./.env
  docker-compose --file docker-compose.yml down
  docker-compose --file docker-compose.yml build test
  docker-compose --file docker-compose.yml run --rm test "dotnet test ./test/ChatApp.Test"
}

while read oldrev newrev refname
do
  zero="0000000000000000000000000000000000000000"
  if [ "$newrev" = "$zero" ]; then
    newrev_type=delete
  else
    newrev_type=$(git cat-file -t $newrev)
  fi
  case "$refname","$newrev_type" in
    refs/heads/*,commit)
      if ! running_test "$newrev" ; then
        exit 1
      fi
      ;;
  esac
done

exit 0
