#!/bin/bash

set -eu

running_test() {
  tempdir=$(mktemp -d)
  trap "[ -e $tempdir ] && rm -rf $tempdir" EXIT
  git archive --format=tar --prefix=chatapp/ "$1" | ( cd "$tempdir" && tar xf - )
  cd "$tempdir/chatapp"
  docker-compose --file docker-compose.yml run test "dotnet test ./test/ChatApp.Test"
}

while read oldrev newrev refname
do
  zero="0000000000000000000000000000000000000000"
  if [ "$newrev" = "$zero" ]; then
    newrev_type=delete
  else
    newrev_type=$(git cat-file -t $newrev)
  fi
  case "$refname","$newrev_type" in
    refs/heads/*,commit)
      if ! running_test "$newrev" ; then
        exit 1
      fi
      ;;
  esac
done

exit 0
